"""Init

Revision ID: d4586b8a1af3
Revises: 
Create Date: 2021-04-29 15:09:33.682148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4586b8a1af3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('creator', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label', 'user', name='_label_user_uc')
    )
    op.create_index(op.f('ix_tags_user'), 'tags', ['user'], unique=False)
    op.create_table('users_max_position',
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('max_pos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user')
    )
    op.create_table('personal_notes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('shared', sa.Boolean(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_notes_position'), 'personal_notes', ['position'], unique=False)
    op.create_index(op.f('ix_personal_notes_user'), 'personal_notes', ['user'], unique=False)
    op.create_table('share_notes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('sync', sa.Boolean(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_note_association',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('pers_note_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['pers_note_id'], ['personal_notes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'pers_note_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_note_association')
    op.drop_table('share_notes')
    op.drop_index(op.f('ix_personal_notes_user'), table_name='personal_notes')
    op.drop_index(op.f('ix_personal_notes_position'), table_name='personal_notes')
    op.drop_table('personal_notes')
    op.drop_table('users_max_position')
    op.drop_index(op.f('ix_tags_user'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('notes')
    # ### end Alembic commands ###
