"""delete confirmed field

Revision ID: 67817cb6048a
Revises: a940109fca51
Create Date: 2021-01-18 20:53:20.213303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67817cb6048a'
down_revision = 'a940109fca51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
