from typing import Optional

from src.entities.note import (NoteCreate, NoteDelete, NoteDeleteToken,
                               NoteFilter, NoteGetItem, NoteImportToken,
                               NoteItem, NoteSetToken, NoteSwapPosition,
                               NoteUpdate, NoteUUID, TagAdd, TagCreate,
                               TagItem, TagRemove, TagsGet)


class NoteStorage:
    def create_note(self, note: NoteCreate) -> NoteItem: ...

    def get_note(self, note: NoteGetItem) -> NoteItem: ...

    def update_note(self, note: NoteUpdate) -> NoteItem: ...

    def delete_note(self, note: NoteDelete) -> NoteUUID: ...

    def get_notes(self, filter: NoteFilter) -> list[NoteItem]: ...

    def swap_notes(self, notes: NoteSwapPosition) -> list[NoteItem]: ...

    def create_tag(self, tag: TagCreate) -> TagItem: ...

    def add_tag(self, tag: TagAdd) -> NoteItem: ...

    def remove_tag(self, tag: TagRemove) -> NoteItem: ...

    def set_token_for_sharing(
        self, note_for_set_token: NoteSetToken) -> Optional[NoteItem]: ...

    def delete_token_for_sharing(
        self, note_for_delete_token: NoteDeleteToken) -> Optional[NoteItem]: ...

    def import_note(self, import_note: NoteImportToken) -> Optional[NoteItem]: ...

    def create_and_add_tag(self, tag: TagAdd) -> NoteItem: ...

    def get_tags(self, to_get_tags: TagsGet) -> list[TagItem]: ...
